version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/taskmanager
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
